### ISSUE TITLE
Cannot add task 'jpackage' as a task with that name already exists.

### ISSUE THREAD

**Issue by fengliulin** [petr-panteleyev/jpackage-gradle-plugin#19]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/44517777/211236684-ed1480ce-9bd4-461e-a612-0e0497ba0cdd.png">

**Comment by petr-panteleyev** [comment]
1. Don't use screenshots for stack traces
2. Provide sample code to reproduce the issue.

Closing as not enough information provided in the issue.
