### ISSUE TITLE
Execution failed for task ':jpackage'

### ISSUE THREAD

**Issue by DenuxPlays** [petr-panteleyev/jpackage-gradle-plugin#23]
Error message:
![image](https://user-images.githubusercontent.com/83671398/223215661-76edbabe-5c0d-4931-8565-4afd83862f85.png)

task:
```kotlin
tasks.jpackage {
    dependsOn(jar, shadowJar)

    input = "$buildDir/libs"
    destination = "$buildDir/dist"

    appName = "OpenFlowcharts"
    vendor = "denux.dev"

    mainJar = tasks.shadowJar.get().archiveFileName.get()
    mainClass = "dev.denux.flowcharts.LaunchHelper"

    javaOptions = listOf("-Dfile.encoding=UTF-8")

    windows {
        winConsole = true
    }
}
```

I have no idea what the issue is due to the error message being useless.
How do I fix this?
Btw. I am using gradle 8 maybe this is causing issues???

**Comment by petr-panteleyev** [comment]
Plugin works with gradle 8, at least I have 1 build that does.
From what I see this is an error happened inside jpackage.exe.
Try to launch the build with --info option and check if there is any diagnostics coming from jpackage.exe.

**Comment by DenuxPlays** [comment]
think I found the error:
![image](https://user-images.githubusercontent.com/83671398/223218722-04c1d693-f625-4ad5-9c23-22adf711d5f1.png)
I'll install it and give you an update asap

**Comment by DenuxPlays** [comment]
That fixed it. 
But I have a feature request:
Can we support this type of versioning:
![image](https://user-images.githubusercontent.com/83671398/223220512-7681991c-2819-42ab-a9a3-2f12d746dabf.png)

**Comment by petr-panteleyev** [comment]
If this version format is rejected by jpackage.exe or installer tool then plugin cannot do anything about this.

**Comment by DenuxPlays** [comment]
Ah okay thank you :)
