### ISSUE TITLE
docs: missing description of javaOptions in README

### ISSUE THREAD

**Issue by miurahr** [petr-panteleyev/jpackage-gradle-plugin#28]
The plugin accepts `jpackage` task parameter `javaOptions`  such as  `javaOptions = ["-Xmx1024M", "--add-opens", "java.desktop/sun.awt.X11=ALL-UNNAMED"]` but it is missing in `README.md` 

Here is a description in jpackage manual.

```
--java-options <java options>
Options to pass to the Java runtime

This option can be used multiple times.
```

**Comment by petr-panteleyev** [comment]
README updated
