### ISSUE TITLE
Jpackage command throwing error 

### ISSUE THREAD

**Issue by Harshul2023** [petr-panteleyev/jpackage-gradle-plugin#32]
jpackage -t exe --description "SpandanApplication" --app-version 2.0 --input . --icon "C:\Users\Sunfo\Downloads\qms_logo.ico" --dest . --name "SpandanApplication" --main-jar Spandan-Desktop-Application-1.0-SNAPSHOT-all.jar --module-path javafx --add-modules javafx.controls,java.naming,javafx.graphics,java.sql,javafx.fxml,javafx.base,java.logging,jdk.crypto.ec --win-shortcut --win-console                            
java.io.IOException: Command [light.exe, -nologo, -spdb, -ext, WixUtilExtension, -out, C:\Users\Sunfo\AppData\Local\Temp\jdk.jpackage10705337875172070368\images\win-exe.image\SpandanApplicatio
n-2.0.msi, -sice:ICE27, -loc, C:\Users\Sunfo\AppData\Local\Temp\jdk.jpackage10705337875172070368\config\MsiInstallerStrings_en.wxl, -cultures:en-us, C:\Users\Sunfo\AppData\Local\Temp\jdk.jpack
age10705337875172070368\wixobj\main.wixobj, C:\Users\Sunfo\AppData\Local\Temp\jdk.jpackage10705337875172070368\wixobj\bundle.wixobj, C:\Users\Sunfo\AppData\Local\Temp\jdk.jpackage10705337875172070368\wixobj\ui.wixobj] in C:\Users\Sunfo\AppData\Local\Temp\jdk.jpackage10705337875172070368\images\win-msi.image\SpandanApplication exited with 103 code
earlier my jpackage command used to work fine  I changed my project structure after then this error is coming in this project if i run jpackage command on other projects it runs fine whan can be the issue. If i change the name and description to small case like"qms" then also it builds the exe but the size is doubled which originally it used to make like before the size of exe was 120 mb not size is coming 250 mb

**Comment by Harshul2023** [comment]
![Screenshot 2023-12-20 123605](https://github.com/petr-panteleyev/jpackage-gradle-plugin/assets/118358350/b540bdcf-c2d8-4542-b7b1-89c05576260b)
png…]()

**Comment by petr-panteleyev** [comment]
Hello. This issue tracker is about jpackage-gradle-plugin. I can't help you with using jpackage itself.
