### ISSUE TITLE
Proposal: support multiple image types

### ISSUE THREAD

**Issue by Zimbrando** [petr-panteleyev/jpackage-gradle-plugin#33]
Sometimes projects want to ship software in both image types supported by jpackage for a determined OS.
I found a way to implement it overriding the `action()` function.

https://github.com/AlchemistSimulator/Alchemist/blob/9d0ba2e8a8264cebf737126051e1615e4bcd1753/alchemist-full/build.gradle.kts#L46-L60

It looks kinda ugly, it could be avoided by supporting a list of types instead of one single type.

**Comment by Achille004** [comment]
@Zimbrando 
Your solution works really well, I did not think of extending it like that.
Thank you very much!
