### ISSUE TITLE
Seems not to work with Gradle 8.4

### ISSUE THREAD

**Issue by upost** [petr-panteleyev/jpackage-gradle-plugin#34]
get() method not recognized
Task not recognized
from()... in two tasks not recognized

I'm not a gradle expert, but unfortunately they seem to change the syntax often, so could you please update your plugin and/or accordingly? Thanks!

**Comment by petr-panteleyev** [comment]
It definitely works with Gradle 8.7, check this project: https://github.com/petr-panteleyev/password-generator

**Comment by upost** [comment]
thanks for closing, so there is no reason for the the error message and it's just something unknown going on.
