### ISSUE TITLE
Add --app-image parameter

### ISSUE THREAD

**Issue by thecodewarrior** [petr-panteleyev/jpackage-gradle-plugin#5]
As part of a project I need to be able to modify the application image, however while I can create an app image by setting the type, it's impossible for me to bundle it.

It might be worthwhile to have an "additional options" parameter to avoid issues like this in the future.

**Comment by nebaughman** [comment]
I think this is achieved with jpackage's `--type app-image` or `type = org.panteleyev.jpackage.ImageType.APP_IMAGE` in groovy.

**Comment by petr-panteleyev** [comment]
v1.1.1

**Comment by nebaughman** [comment]
> That's the parameter for _creating_ an application image. The `--app-image` parameter is necessary to _use_ that image in an installer bundle. (See section 5.1 of the [Packaging Tool User's Guide](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-tool-user-guide.pdf))

Yes, ideed! Thank you for the clarification.
