### ISSUE TITLE
Adding the plugin to build.gradle

### ISSUE THREAD

**Issue by faocrates** [petr-panteleyev/jpackage-gradle-plugin#8]
Hello, I haven't been able to add this plugin to my gradle-based project and I can't see any relevant information. Is there any example build.gradle showing how I can integrate it?

**Comment by faocrates** [comment]
After some experimentation / trial and error, I got the basic build.gradle (non-modular) integration running as below. If you have any other example or advice I would appreciate if you share.

```
plugins {
  ...
  id "org.panteleyev.jpackageplugin" version "1.3.1"
}
...
task copyDependencies(type: Copy) {
    from(configurations.runtimeClasspath).into("$buildDir/jars")
}

task copyJar(type: Copy) {
    from(tasks.jar).into("$buildDir/jars")
}

tasks.jpackage {
    dependsOn("build", "copyDependencies", "copyJar")

    input  = "$buildDir/jars"
    destination = "$buildDir/dist"

    appName = "Mine"
    appVersion = "1.0.0"
    vendor = "company.com"

    mainJar = 'mine.jar'
    mainClass = "com.company.ui.Main"

    javaOptions = Arrays.asList("-Dfile.encoding=UTF-8")

    windows {
        winConsole = true
    }
}
```

**Comment by petr-panteleyev** [comment]
There is an example at the bottom of the readme.
Plugin itself is included as usual:
https://plugins.gradle.org/plugin/org.panteleyev.jpackageplugin

**Comment by faocrates** [comment]
Yes I saw the two examples although I guess they use a Kotlin syntax, the above runs fine in Gradle/Groovy.

**Comment by petr-panteleyev** [comment]
I'm not interested in Groovy DSL.
